FROM ruby:3.2.3-slim

WORKDIR /rails

ENV RAILS_ENV=development \
    BUNDLE_WITHOUT="" \
    BUNDLE_PATH=/usr/local/bundle \
    REDIS_URL=redis://redis:6379/1

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git curl default-libmysqlclient-dev libvips pkg-config && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-lc", "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"]
