SCHEDULE_MESSAGE_NEW      = 0.freeze
SCHEDULE_MESSAGE_SENDED   = 1.freeze
SCHEDULE_MESSAGE_FAIL     = 2.freeze

LOG_ADMIN                 = 0.freeze
LOG_USER                  = 10.freeze
LOG_USERCOIN              = 11.freeze
LOG_USERCOUPON            = 12.freeze
LOG_USERFRIEND            = 13.freeze
LOG_SHOP                  = 30.freeze
LOG_SHOPCOUPON            = 31.freeze
LOG_REQUEST               = 40.freeze
LOG_REQUEST_CATEGORY      = 41.freeze
LOG_MESSAGE               = 50.freeze

LOG_TYPE_TEXT = {
    LOG_ADMIN             => "管理者",
    LOG_USER              => "使用者",
    LOG_USERCOIN          => "柑幣",
    LOG_USERCOUPON        => "使用者優惠卷",
    LOG_USERFRIEND        => "使用者朋友",
    LOG_SHOP              => "商家",
    LOG_SHOPCOUPON        => "商家優惠卷",
    LOG_REQUEST           => "派工",
    LOG_REQUEST_CATEGORY  => "派工類別",
    LOG_MESSAGE           => "訊息推撥"
}

ACTION_NEW                = 0.freeze
ACTION_ADD                = 1.freeze
ACTION_DEL                = 2.freeze
ACTION_EDIT               = 3.freeze
ACTION_BLOCK              = 4.freeze

LOG_ACTION_TEXT = {
    ACTION_NEW            => "新增",
    ACTION_ADD            => "增加",
    ACTION_DEL            => "刪除",
    ACTION_EDIT           => "編輯",
    ACTION_BLOCK          => "封鎖"
}

COINS_GET_SYSTEM          = 0.freeze
COINS_GET_REQUEST         = 1.freeze
COINS_GET_FRIEND          = 2.freeze
COINS_GET_BONUS           = 3.freeze
COINS_USE_CATEGORY        = 50.freeze
COINS_USE_COUPON          = 50.freeze

REQUEST_NEW               = 0.freeze
REQUEST_ACCEPTED          = 1.freeze
REQUEST_FINISH            = 2.freeze
REQUEST_EXPIRED           = 3.freeze

CITY_CODE = [
    {city: "台北市" , code: 1 },
    {city: "基隆市" , code: 2 },
    {city: "新北市" , code: 3 },
    {city: "宜蘭縣" , code: 4 },
    {city: "新竹市" , code: 5 },
    {city: "新竹縣" , code: 6 },
    {city: "桃園市" , code: 7 },
    {city: "苗栗縣" , code: 8 },
    {city: "臺中市" , code: 9 },
    {city: "彰化縣" , code: 10 },
    {city: "南投縣" , code: 11 },
    {city: "嘉義市" , code: 12 },
    {city: "嘉義縣" , code: 13 },
    {city: "雲林縣" , code: 14 },
    {city: "臺南市" , code: 15 },
    {city: "高雄市" , code: 16 },
    {city: "屏東縣" , code: 17 },
    {city: "臺東縣" , code: 18 },
    {city: "花蓮縣" , code: 19 },
    {city: "澎湖縣" , code: 20 },
    {city: "金門縣" , code: 21 },
    {city: "連江縣" , code: 22 },
    {city: "南海島" , code: 23 },
    {city: "釣魚臺" , code: 24 },
]


POSTAL_CODE = [
    # 台北市
    {city: 1, name: "中正區", code: 100},
    {city: 1, name: "大同區", code: 103},
    {city: 1, name: "中山區", code: 104},
    {city: 1, name: "松山區", code: 105},
    {city: 1, name: "大安區", code: 106},
    {city: 1, name: "萬華區", code: 108},
    {city: 1, name: "信義區", code: 110},
    {city: 1, name: "士林區", code: 111},
    {city: 1, name: "北投區", code: 112},
    {city: 1, name: "內湖區", code: 114},
    {city: 1, name: "南港區", code: 115},
    {city: 1, name: "文山區", code: 116},
    # 基隆市
    {city: 2, name: "仁愛區", code: 200},
    {city: 2, name: "信義區", code: 201},
    {city: 2, name: "中正區", code: 202},
    {city: 2, name: "中山區", code: 203},
    {city: 2, name: "安樂區", code: 204},
    {city: 2, name: "暖暖區", code: 205},
    {city: 2, name: "七堵區", code: 206},
    # 新北市
    {city: 3, name: "萬里區", code: 207},
    {city: 3, name: "金山區", code: 208},
    {city: 3, name: "板橋區", code: 220},
    {city: 3, name: "汐止區", code: 221},
    {city: 3, name: "深坑區", code: 222},
    {city: 3, name: "石碇區", code: 223},
    {city: 3, name: "瑞芳區", code: 224},
    {city: 3, name: "平溪區", code: 226},
    {city: 3, name: "雙溪區", code: 227},
    {city: 3, name: "貢寮區", code: 228},
    {city: 3, name: "新店區", code: 231},
    {city: 3, name: "坪林區", code: 232},
    {city: 3, name: "烏來區", code: 233},
    {city: 3, name: "永和區", code: 234},
    {city: 3, name: "中和區", code: 235},
    {city: 3, name: "土城區", code: 236},
    {city: 3, name: "三峽區", code: 237},
    {city: 3, name: "樹林區", code: 238},
    {city: 3, name: "鶯歌區", code: 239},
    {city: 3, name: "三重區", code: 241},
    {city: 3, name: "新莊區", code: 242},
    {city: 3, name: "泰山區", code: 243},
    {city: 3, name: "林口區", code: 244},
    {city: 3, name: "蘆洲區", code: 247},
    {city: 3, name: "五股區", code: 248},
    {city: 3, name: "八里區", code: 249},
    {city: 3, name: "淡水區", code: 251},
    {city: 3, name: "三芝區", code: 252},
    {city: 3, name: "石門區", code: 253},
    # 宜蘭縣
    {city: 4, name: "宜蘭市", code: 260},
    {city: 4, name: "頭城鎮", code: 261},
    {city: 4, name: "礁溪鄉", code: 262},
    {city: 4, name: "壯圍鄉", code: 263},
    {city: 4, name: "員山鄉", code: 264},
    {city: 4, name: "羅東鎮", code: 265},
    {city: 4, name: "三星鄉", code: 266},
    {city: 4, name: "大同鄉", code: 267},
    {city: 4, name: "五結鄉", code: 268},
    {city: 4, name: "冬山鄉", code: 269},
    {city: 4, name: "蘇澳鎮", code: 270},
    {city: 4, name: "南澳鄉", code: 272},
    # 新竹市
    {city: 5, name: "東  區", code: 300}, # 300
    {city: 5, name: "北  區", code: 317}, # 300
    {city: 5, name: "香山區", code: 318}, # 300
    # 新竹縣
    {city: 6, name: "竹北市", code: 302},
    {city: 6, name: "湖口鄉", code: 303},
    {city: 6, name: "新豐鄉", code: 304},
    {city: 6, name: "新埔鎮", code: 305},
    {city: 6, name: "關西鎮", code: 306},
    {city: 6, name: "芎林鄉", code: 307},
    {city: 6, name: "寶山鄉", code: 308},
    {city: 6, name: "竹東鎮", code: 310},
    {city: 6, name: "五峰鄉", code: 311},
    {city: 6, name: "橫山鄉", code: 312},
    {city: 6, name: "尖石鄉", code: 313},
    {city: 6, name: "北埔鄉", code: 314},
    {city: 6, name: "峨眉鄉", code: 315},
    # 桃園市
    {city: 7, name: "中壢區", code: 320},
    {city: 7, name: "平鎮區", code: 324},
    {city: 7, name: "龍潭區", code: 325},
    {city: 7, name: "楊梅區", code: 326},
    {city: 7, name: "新屋區", code: 327},
    {city: 7, name: "觀音區", code: 328},
    {city: 7, name: "桃園區", code: 330},
    {city: 7, name: "龜山區", code: 333},
    {city: 7, name: "八德區", code: 334},
    {city: 7, name: "大溪區", code: 335},
    {city: 7, name: "復興區", code: 336},
    {city: 7, name: "大園區", code: 337},
    {city: 7, name: "蘆竹區", code: 338},
    # 苗栗縣
    {city: 8, name: "竹南鎮", code: 350},
    {city: 8, name: "頭份市", code: 351},
    {city: 8, name: "三灣鄉", code: 352},
    {city: 8, name: "南庄鄉", code: 353},
    {city: 8, name: "獅潭鄉", code: 354},
    {city: 8, name: "後龍鎮", code: 356},
    {city: 8, name: "通霄鎮", code: 357},
    {city: 8, name: "苑裡鎮", code: 358},
    {city: 8, name: "苗栗市", code: 360},
    {city: 8, name: "造橋鄉", code: 361},
    {city: 8, name: "頭屋鄉", code: 362},
    {city: 8, name: "公館鄉", code: 363},
    {city: 8, name: "大湖鄉", code: 364},
    {city: 8, name: "泰安鄉", code: 365},
    {city: 8, name: "銅鑼鄉", code: 366},
    {city: 8, name: "三義鄉", code: 367},
    {city: 8, name: "西湖鄉", code: 368},
    {city: 8, name: "卓蘭鎮", code: 369},
    # 臺中市
    {city: 9, name: "中　區", code: 400},
    {city: 9, name: "東　區", code: 401},
    {city: 9, name: "南　區", code: 402},
    {city: 9, name: "西　區", code: 403},
    {city: 9, name: "北　區", code: 404},
    {city: 9, name: "北屯區", code: 406},
    {city: 9, name: "西屯區", code: 407},
    {city: 9, name: "南屯區", code: 408},
    {city: 9, name: "太平區", code: 411},
    {city: 9, name: "大里區", code: 412},
    {city: 9, name: "霧峰區", code: 413},
    {city: 9, name: "烏日區", code: 414},
    {city: 9, name: "豐原區", code: 420},
    {city: 9, name: "后里區", code: 421},
    {city: 9, name: "石岡區", code: 422},
    {city: 9, name: "東勢區", code: 423},
    {city: 9, name: "和平區", code: 424},
    {city: 9, name: "新社區", code: 426},
    {city: 9, name: "潭子區", code: 427},
    {city: 9, name: "大雅區", code: 428},
    {city: 9, name: "神岡區", code: 429},
    {city: 9, name: "大肚區", code: 432},
    {city: 9, name: "沙鹿區", code: 433},
    {city: 9, name: "龍井區", code: 434},
    {city: 9, name: "梧棲區", code: 435},
    {city: 9, name: "清水區", code: 436},
    {city: 9, name: "大甲區", code: 437},
    {city: 9, name: "外埔區", code: 438},
    {city: 9, name: "大安區", code: 439},
    # 彰化縣
    {city: 10, name: "彰化市", code: 500},
    {city: 10, name: "芬園鄉", code: 502},
    {city: 10, name: "花壇鄉", code: 503},
    {city: 10, name: "秀水鄉", code: 504},
    {city: 10, name: "鹿港鎮", code: 505},
    {city: 10, name: "福興鄉", code: 506},
    {city: 10, name: "線西鄉", code: 507},
    {city: 10, name: "和美鎮", code: 508},
    {city: 10, name: "伸港鄉", code: 509},
    {city: 10, name: "員林鎮", code: 510},
    {city: 10, name: "社頭鄉", code: 511},
    {city: 10, name: "永靖鄉", code: 512},
    {city: 10, name: "埔心鄉", code: 513},
    {city: 10, name: "溪湖鎮", code: 514},
    {city: 10, name: "大村鄉", code: 515},
    {city: 10, name: "埔鹽鄉", code: 516},
    {city: 10, name: "田中鎮", code: 520},
    {city: 10, name: "北斗鎮", code: 521},
    {city: 10, name: "田尾鄉", code: 522},
    {city: 10, name: "埤頭鄉", code: 523},
    {city: 10, name: "溪州鄉", code: 524},
    {city: 10, name: "竹塘鄉", code: 525},
    {city: 10, name: "二林鎮", code: 526},
    {city: 10, name: "大城鄉", code: 527},
    {city: 10, name: "芳苑鄉", code: 528},
    {city: 10, name: "二水鄉", code: 530},
    # 南投縣
    {city: 11, name: "南投市", code: 540},
    {city: 11, name: "中寮鄉", code: 541},
    {city: 11, name: "草屯鎮", code: 542},
    {city: 11, name: "國姓鄉", code: 544},
    {city: 11, name: "埔里鎮", code: 545},
    {city: 11, name: "仁愛鄉", code: 546},
    {city: 11, name: "名間鄉", code: 551},
    {city: 11, name: "集集鎮", code: 552},
    {city: 11, name: "水里鄉", code: 553},
    {city: 11, name: "魚池鄉", code: 555},
    {city: 11, name: "信義鄉", code: 556},
    {city: 11, name: "竹山鎮", code: 557},
    {city: 11, name: "鹿谷鄉", code: 558},
    # 嘉義市
    {city: 12, name: "東　區", code: 600}, # 600
    {city: 12, name: "西　區", code: 601}, # 600
    # 嘉義縣
    {city: 13, name: "番路鄉", code: 602},
    {city: 13, name: "梅山鄉", code: 603},
    {city: 13, name: "竹崎鄉", code: 604},
    {city: 13, name: "阿里山", code: 605},
    {city: 13, name: "中埔鄉", code: 606},
    {city: 13, name: "大埔鄉", code: 607},
    {city: 13, name: "水上鄉", code: 608},
    {city: 13, name: "鹿草鄉", code: 611},
    {city: 13, name: "太保市", code: 612},
    {city: 13, name: "朴子市", code: 613},
    {city: 13, name: "東石鄉", code: 614},
    {city: 13, name: "六腳鄉", code: 615},
    {city: 13, name: "新港鄉", code: 616},
    {city: 13, name: "民雄鄉", code: 621},
    {city: 13, name: "大林鎮", code: 622},
    {city: 13, name: "溪口鄉", code: 623},
    {city: 13, name: "義竹鄉", code: 624},
    {city: 13, name: "布袋鎮", code: 625},
    # 雲林縣
    {city: 14, name: "斗南鎮", code: 630},
    {city: 14, name: "大埤鄉", code: 631},
    {city: 14, name: "虎尾鎮", code: 632},
    {city: 14, name: "土庫鎮", code: 633},
    {city: 14, name: "褒忠鄉", code: 634},
    {city: 14, name: "東勢鄉", code: 635},
    {city: 14, name: "臺西鄉", code: 636},
    {city: 14, name: "崙背鄉", code: 637},
    {city: 14, name: "麥寮鄉", code: 638},
    {city: 14, name: "斗六市", code: 640},
    {city: 14, name: "林內鄉", code: 643},
    {city: 14, name: "古坑鄉", code: 646},
    {city: 14, name: "莿桐鄉", code: 647},
    {city: 14, name: "西螺鎮", code: 648},
    {city: 14, name: "二崙鄉", code: 649},
    {city: 14, name: "北港鎮", code: 651},
    {city: 14, name: "水林鄉", code: 652},
    {city: 14, name: "口湖鄉", code: 653},
    {city: 14, name: "四湖鄉", code: 654},
    {city: 14, name: "元長鄉", code: 655},
    # 臺南市
    {city: 15, name: "中西區", code: 700},
    {city: 15, name: "東　區", code: 701},
    {city: 15, name: "南　區", code: 702},
    {city: 15, name: "北　區", code: 704},
    {city: 15, name: "安平區", code: 708},
    {city: 15, name: "安南區", code: 709},
    {city: 15, name: "永康區", code: 710},
    {city: 15, name: "歸仁區", code: 711},
    {city: 15, name: "新化區", code: 712},
    {city: 15, name: "左鎮區", code: 713},
    {city: 15, name: "玉井區", code: 714},
    {city: 15, name: "楠西區", code: 715},
    {city: 15, name: "南化區", code: 716},
    {city: 15, name: "仁德區", code: 717},
    {city: 15, name: "關廟區", code: 718},
    {city: 15, name: "龍崎區", code: 719},
    {city: 15, name: "官田區", code: 720},
    {city: 15, name: "麻豆區", code: 721},
    {city: 15, name: "佳里區", code: 722},
    {city: 15, name: "西港區", code: 723},
    {city: 15, name: "七股區", code: 724},
    {city: 15, name: "將軍區", code: 725},
    {city: 15, name: "學甲區", code: 726},
    {city: 15, name: "北門區", code: 727},
    {city: 15, name: "新營區", code: 730},
    {city: 15, name: "後壁區", code: 731},
    {city: 15, name: "白河區", code: 732},
    {city: 15, name: "東山區", code: 733},
    {city: 15, name: "六甲區", code: 734},
    {city: 15, name: "下營區", code: 735},
    {city: 15, name: "柳營區", code: 736},
    {city: 15, name: "鹽水區", code: 737},
    {city: 15, name: "善化區", code: 741},
    {city: 15, name: "大內區", code: 742},
    {city: 15, name: "山上區", code: 743},
    {city: 15, name: "新市區", code: 744},
    {city: 15, name: "安定區", code: 745},
    # 高雄市
    {city: 16, name: "新興區", code: 800},
    {city: 16, name: "前金區", code: 801},
    {city: 16, name: "苓雅區", code: 802},
    {city: 16, name: "鹽埕區", code: 803},
    {city: 16, name: "鼓山區", code: 804},
    {city: 16, name: "旗津區", code: 805},
    {city: 16, name: "前鎮區", code: 806},
    {city: 16, name: "三民區", code: 807},
    {city: 16, name: "楠梓區", code: 811},
    {city: 16, name: "小港區", code: 812},
    {city: 16, name: "左營區", code: 813},
    {city: 16, name: "仁武區", code: 814},
    {city: 16, name: "大社區", code: 815},
    {city: 16, name: "岡山區", code: 820},
    {city: 16, name: "路竹區", code: 821},
    {city: 16, name: "阿蓮區", code: 822},
    {city: 16, name: "田寮區", code: 823},
    {city: 16, name: "燕巢區", code: 824},
    {city: 16, name: "橋頭區", code: 825},
    {city: 16, name: "梓官區", code: 826},
    {city: 16, name: "彌陀區", code: 827},
    {city: 16, name: "永安區", code: 828},
    {city: 16, name: "湖內區", code: 829},
    {city: 16, name: "鳳山區", code: 830},
    {city: 16, name: "大寮區", code: 831},
    {city: 16, name: "林園區", code: 832},
    {city: 16, name: "鳥松區", code: 833},
    {city: 16, name: "大樹區", code: 840},
    {city: 16, name: "旗山區", code: 842},
    {city: 16, name: "美濃區", code: 843},
    {city: 16, name: "六龜區", code: 844},
    {city: 16, name: "內門區", code: 845},
    {city: 16, name: "杉林區", code: 846},
    {city: 16, name: "甲仙區", code: 847},
    {city: 16, name: "桃源區", code: 848},
    {city: 16, name: "那瑪夏", code: 849},
    {city: 16, name: "茂林區", code: 851},
    {city: 16, name: "茄萣區", code: 852},
    # 屏東縣
    {city: 17, name: "屏東市", code: 900},
    {city: 17, name: "三地門", code: 901},
    {city: 17, name: "霧臺鄉", code: 902},
    {city: 17, name: "瑪家鄉", code: 903},
    {city: 17, name: "九如鄉", code: 904},
    {city: 17, name: "里港鄉", code: 905},
    {city: 17, name: "高樹鄉", code: 906},
    {city: 17, name: "鹽埔鄉", code: 907},
    {city: 17, name: "長治鄉", code: 908},
    {city: 17, name: "麟洛鄉", code: 909},
    {city: 17, name: "竹田鄉", code: 911},
    {city: 17, name: "內埔鄉", code: 912},
    {city: 17, name: "萬丹鄉", code: 913},
    {city: 17, name: "潮州鎮", code: 920},
    {city: 17, name: "泰武鄉", code: 921},
    {city: 17, name: "來義鄉", code: 922},
    {city: 17, name: "萬巒鄉", code: 923},
    {city: 17, name: "崁頂鄉", code: 924},
    {city: 17, name: "新埤鄉", code: 925},
    {city: 17, name: "南州鄉", code: 926},
    {city: 17, name: "林邊鄉", code: 927},
    {city: 17, name: "東港鎮", code: 928},
    {city: 17, name: "琉球鄉", code: 929},
    {city: 17, name: "佳冬鄉", code: 931},
    {city: 17, name: "新園鄉", code: 932},
    {city: 17, name: "枋寮鄉", code: 940},
    {city: 17, name: "枋山鄉", code: 941},
    {city: 17, name: "春日鄉", code: 942},
    {city: 17, name: "獅子鄉", code: 943},
    {city: 17, name: "車城鄉", code: 944},
    {city: 17, name: "牡丹鄉", code: 945},
    {city: 17, name: "恆春鎮", code: 946},
    {city: 17, name: "滿州鄉", code: 947},
    # 臺東縣
    {city: 18, name: "臺東市", code: 950},
    {city: 18, name: "綠島鄉", code: 951},
    {city: 18, name: "蘭嶼鄉", code: 952},
    {city: 18, name: "延平鄉", code: 953},
    {city: 18, name: "卑南鄉", code: 954},
    {city: 18, name: "鹿野鄉", code: 955},
    {city: 18, name: "關山鎮", code: 956},
    {city: 18, name: "海端鄉", code: 957},
    {city: 18, name: "池上鄉", code: 958},
    {city: 18, name: "東河鄉", code: 959},
    {city: 18, name: "成功鎮", code: 961},
    {city: 18, name: "長濱鄉", code: 962},
    {city: 18, name: "太麻里", code: 963},
    {city: 18, name: "金峰鄉", code: 964},
    {city: 18, name: "大武鄉", code: 965},
    {city: 18, name: "達仁鄉", code: 966},
    # 花蓮縣
    {city: 19, name: "花蓮市", code: 970},
    {city: 19, name: "新城鄉", code: 971},
    {city: 19, name: "秀林鄉", code: 972},
    {city: 19, name: "吉安鄉", code: 973},
    {city: 19, name: "壽豐鄉", code: 974},
    {city: 19, name: "鳳林鎮", code: 975},
    {city: 19, name: "光復鄉", code: 976},
    {city: 19, name: "豐濱鄉", code: 977},
    {city: 19, name: "瑞穗鄉", code: 978},
    {city: 19, name: "萬榮鄉", code: 979},
    {city: 19, name: "玉里鎮", code: 981},
    {city: 19, name: "卓溪鄉", code: 982},
    {city: 19, name: "富里鄉", code: 983},
    # 澎湖縣
    {city: 20, name: "馬公市", code: 880},
    {city: 20, name: "西嶼鄉", code: 881},
    {city: 20, name: "望安鄉", code: 882},
    {city: 20, name: "七美鄉", code: 883},
    {city: 20, name: "白沙鄉", code: 884},
    {city: 20, name: "湖西鄉", code: 885},
    # 金門縣
    {city: 21, name: "金沙鎮", code: 890},
    {city: 21, name: "金湖鎮", code: 891},
    {city: 21, name: "金寧鄉", code: 892},
    {city: 21, name: "金城鎮", code: 893},
    {city: 21, name: "烈嶼鄉", code: 894},
    {city: 21, name: "烏坵鄉", code: 896},
    # 連江縣
    {city: 22, name: "南竿鄉", code: 209},
    {city: 22, name: "北竿鄉", code: 210},
    {city: 22, name: "莒光鄉", code: 211},
    {city: 22, name: "東引鄉", code: 212},
    # 南海島
    {city: 23, name: "東沙群島", code: 817},
    {city: 23, name: "南沙群島", code: 819},
    # 釣魚臺
    {city: 24, name: "釣魚臺", code: 290},
]


COUPON_USE_RULE_DEFAULT = [
"商品優惠券使用方式及注意事項,1). 本券可在實體門市及網路門市使用，適用於所有商品（包括特價品或福利品）。2). 本券限會員兌換，每張僅限使用一次，使用後即失效。3). 本券不得轉售、兌換現金、找零或折換其他贈品，亦不可抵用維修費及運費。4). 若非因商品瑕疵而退換貨，所使用的抵用券即失效，需補足商品價差。5). 本券僅適用於活動期間，逾期無效。6). 本券不得與其他折扣、優惠或行銷活動合併使用。7). 使用本券購買商品的交易不開具發票，開立發票的金額以實際支付的金額為準。8). 本公司保留對活動條款及商品優惠券使用規則進行調整和變更的權利，所有變動請以商家公告為準。9). 使用本券時，如有任何疑問，請聯繫客服部門。10). 本券適用範圍及條件以商家公告為準，如有異議，以商家最終解釋為準。",
]

SHOP_CATEGORY_CODE = [
    {name: "others",   category: "其他",    code: 0, icon: "fas fa-store",          color: "#82702b", heml_font: '<i class="fas fa-store"></i>'},
    {name: "traffic",  category: "行",     code: 1, icon: "fas fa-car",            color: "#02d142", heml_font: '<i class="fas fa-car"></i>'},
    {name: "dining",   category: "食",     code: 2, icon: "fas fa-utensils",       color: "#558B2F", heml_font: '<i class="fas fa-utensils"></i>'},
    {name: "playing",  category: "育",     code: 3, icon: "fas fa-laugh-beam",    color: "#7B1FA2", heml_font: '<i class="fas fa-laugh-beam"></i>'},
    {name: "hostel",   category: "住",      code: 4, icon: "fas fa-hostel",         color: "#7B1FA2", heml_font: '<i class="fas fa-hostel"></i>'},
    {name: "medical",  category: "醫療",    code: 5, icon: "fas fa-clinic-medical", color: "#F44336", heml_font: '<i class="fas fa-clinic-medical"></i>'},
    {name: "shopping", category: "購物",    code: 6, icon: "fas fa-shopping-cart",  color: "#0288D1", heml_font: '<i class="fas fa-shopping-cart"></i>'},
    {name: "bank",     category: "銀行",    code: 7, icon: "fas fa-university",     color: "#FF9800",  heml_font: '<i class="fas fa-university"></i>'},
    {name: "care",     category: "樂齡友善",code: 8, icon: "fas fa-star",          color: "#02d142", heml_font: '<i class="fas fa-star"></i>'},
#    {name: "clothing", category: "服飾",    code: 9, icon: "fas fa-tshirt",         color: "#F44336", heml_font: '<i class="fas fa-tshirt"></i>'},
#    {name: "service",  category: "生活服務",code: 10, icon: "fas fa-user-tie",       color: "#FF9800", heml_font: '<i class="fas fa-user-tie"></i>'},
#    {name: "store",    category: "生活用品",code: 11, icon: "fas fa-shopping-bag",  color: "#7B1FA2", heml_font: '<i class="fas fa-shopping-bag"></i>'},
#    {name: "parking",  category: "停車",    code: 12, icon: "fas fa-parking",        color: "#02d142", heml_font: '<i class="fas fa-parking"></i>'},
#    {name: "educate",  category: "教育",    code: 13, icon: "fas fa-school",         color: "#558B2F", heml_font: '<i class="fas fa-school"></i>'},
]
