Sidekiq.strict_args!(false)

LINE_MSG_TYPE_TEXT          = 0
LINE_MSG_TYPE_STAICKER      = 1
LINE_MSG_TYPE_IMAGE         = 2
LINE_MSG_TYPE_VIDEO         = 3
LINE_MSG_TYPE_AUDIO         = 4
LINE_MSG_TYPE_LOCATION      = 5
LINE_MSG_TYPE_IMAGEMAP      = 6
LINE_MSG_TYPE_TEMPLATE      = 7
LINE_MSG_TYPE_FLEX          = 8
