# MySQL. Versions 5.5.8 and up are supported.
#
#   Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: sa
  password: taiwan
  host: db
  port: 3306

development:
  <<: *default
  database: padifield_development

production:
  <<: *default
  database: padifield_production
  username: sa
  password: taiwan
