default: &default_settings
  site_name: "稻相顧"
  site_name_eng: "padifield"
  #site_host: "caregiver.admin.miaoligo.com"
  #site_email_host: "caregiver.com"
  #site_email: "service@caregiver.com"

  admin_subdomain: "padifieldadmin"
  app_path: "line"

  health_view_url: "https://phslineweb.taiyidigital.com/App"

  line_at_url: "https://liff.line.me/1645278921-kWRPP32q/?accountId=233owasl"

  line_authorize_url: "https://access.line.me/oauth2/v2.1/authorize"
  line_api_token_url: "https://api.line.me/oauth2/v2.1/token"
  line_api_verify_url: "https://api.line.me/oauth2/v2.1/verify"

  line_login_channel_id: "2006848648"
  line_login_Channel_secret: "45c7c39f0fac242335b05d421af03b0e"
  line_login_callback_url: "https://padifield.hopto.org/callback"

  line_message_api_channel_id: "2006848439"
  line_message_api_channel_secret: "f998cf3afa2fefbdd120e98a763eb5a5"
  line_message_api_channel_token: "iFRLruIPxX9DybWtIZmqe4ChcbJeT9kFNsBEvsA0XrOxBBbgg1VmpVIr3WOfp4/n47TYrYhxbMoFbkoedglXIR6zQpPHyRHQvjufI+dXrbpwOWrVy1vYkUW20cIKhrA1LatLJz+ExHCXBqM1MgjNNgdB04t89/1O/w1cDnyilFU="
  line_message_api_callback_url: "https://padifield.hopto.org/line_notify"

  line_liff_id: "2004751931-1jrD53LP"
  line_liff_url: "https://liff.line.me/2004751931-POn4oBxp"

  google_map_key: "AIzaSyAIrjnyChM8LHj1xInbMWFlGye5LxFaatU"

  token_secret: "9c0d6b9d-5c3b-4d0b-9e0d-6b9d5c3b0d3b"

development:
  <<: *default_settings

production:
  site_name: "稻相顧"
  site_name_eng: "padifield"
  #site_host: "caregiver.admin.miaoligo.com"
  #site_email_host: "caregiver.com"
  #site_email: "service@caregiver.com"

  admin_subdomain: "padifieldadmin"
  app_path: "line"

  health_view_url: "https://phslineweb.taiyidigital.com/App"

  line_at_url: "https://lin.ee/2Va3G4i"

  line_authorize_url: "https://access.line.me/oauth2/v2.1/authorize"
  line_api_token_url: "https://api.line.me/oauth2/v2.1/token"
  line_api_verify_url: "https://api.line.me/oauth2/v2.1/verify"

  line_login_channel_id: "2006848648"
  line_login_Channel_secret: "45c7c39f0fac242335b05d421af03b0e"
  line_login_callback_url: "https://padifield.hopto.org/callback"

  line_message_api_channel_id: "2006848439"
  line_message_api_channel_secret: "f998cf3afa2fefbdd120e98a763eb5a5"
  line_message_api_channel_token: "iFRLruIPxX9DybWtIZmqe4ChcbJeT9kFNsBEvsA0XrOxBBbgg1VmpVIr3WOfp4/n47TYrYhxbMoFbkoedglXIR6zQpPHyRHQvjufI+dXrbpwOWrVy1vYkUW20cIKhrA1LatLJz+ExHCXBqM1MgjNNgdB04t89/1O/w1cDnyilFU="
  line_message_api_callback_url: "https://padifield.hopto.org/callback"

  line_liff_id: "2005495451-9LQ3bkab"
  line_liff_url: "https://liff.line.me/2005495451-9LQ3bkab"

  google_map_key: "AIzaSyAIrjnyChM8LHj1xInbMWFlGye5LxFaatU"

  token_secret: "9c0d6b9d-5c3b-4d0b-9e0d-6b9d5c3b0d3b"
