:scheduler:
  :schedule:
    daily_check:
      cron: "0 1 * * *"
      class: DailyCheck
      queue: default
    crawler_health_report:
      cron: "*/5 * * * *" 
      class: UpdateHealthReport
      queue: default
