:scheduler:
  :schedule:
    daily_check:
      cron: "0 1 * * *"
      class: DailyCheck
      queue: default
    crawler_health_report:
      cron: "*/2 * * * *" 
      class: UpdateHealthReport # 處理 CM005 西勢社區
      queue: default
    crawler_health_asus_report:
      cron: "*/5 * * * *"
      class: UpdateAsusReport # 處理 CM001 中庄和 CM004 花壇的社區
      queue: default
